language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19.2
services:
  - postgresql
before_script:
  - "cd apps/quest_api && mix do deps.get, deps.compile"
  - "cd apps/quest_admin && mix do deps.get, deps.compile"
  - "cd apps/quest_web && mix do deps.get, deps.compile"
  - mix ecto.create
  - mix ecto.migrate
